import{a as p,i,S as u}from"./assets/vendor-CsZapx_M.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function l(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=l(e);fetch(e.href,s)}})();const d=r=>p.get("https://pixabay.com/api/",{params:{key:"49241808-b19f3ed80577ae196aabc5d53",image_type:"photo",orientation:"horizontal",safesearch:"true",q:r}}).then(t=>t.data.hits),F=document.querySelector(".gallery"),n=[],f=r=>{r.forEach(t=>{const{webformatURL:l,largeImageURL:a,tags:e,likes:s,views:o,comments:m,downloads:A}=t;return n.push(`<li class="gallery-item">
         <a class="gallery-link" href="${a}">
           <img
             class="gallery-image"
             src="${l}"
             alt="${e}"
           />
           <ul class="desc">
               <li class="descel"><span class="bold">Likes:</span> ${s}</li>
               <li class="descel"><span class="bold">Views:</span> ${o}</li>
               <li class="descel"><span class="bold">Comments:</span> ${m}</li>
               <li class="descel"><span class="bold">Downloads:</span> ${A}</li>
             </ul>
         </a>
       </li>`)}),F.insertAdjacentHTML("beforeend",n.join(""))},c="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEZSURBVHgBrZVRDoMgDIar0fi6m2xH2Y3Ek2w3cFfZXXwBljFQCai0xemfoCaU/xNpKwAirXWrlDY5w8ViPhVmbgwIO14A3zeQKq/2IuwaqOu6A07+zaVUT8iUi+V28rd5NuSIOQs5wxyFUOZKqRtnmIpZQCZz3acWcgcXUjkF0b2bmwFSpAxskMAgYecaWSsFC8AgnHkMqIBR09TCGrnHsZic5iLs3By3ngWsITMgy9yphEyVJZjUM6esHUS9yfea7N7DAmJz/1niM2EhVBZR2UKl8DS/SFO80OhUnCBkoYWgz2MdNAx8q0jFOK/Fy1GQvdqYe50BQc3PgLDmRyCU+aYOfFsoCtPa+yXvp2/ue9rHqLATflCf5QflVUcNIrzeSwAAAABJRU5ErkJggg==",h=document.querySelector(".form"),g=document.querySelector("[name=search-text]"),y=document.querySelector(".gallery");h.addEventListener("submit",r=>{if(r.preventDefault(),y.innerHTML="",g.value.trim().length===0){i.show({title:"Error",message:"Please enter your request",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:c,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}d(g.value).then(t=>{if(t.length===0){i.show({title:"😢",message:"Sorry, there are no images matching your search query. Please try again!",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:c,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}console.log(t),f(t),w.refresh()}).catch(t=>{console.log(t)})});let w=new u(".gallery a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=index.js.map
