import{a as u,i,S as p}from"./assets/vendor-CsZapx_M.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const F=o=>u.get("https://pixabay.com/api/",{params:{key:"49241808-b19f3ed80577ae196aabc5d53",image_type:"photo",orientation:"horizontal",safesearch:"true",q:o}}).then(r=>r.data.hits),f=document.querySelector(".gallery"),n=[],h=o=>{o.forEach(r=>{const{webformatURL:s,largeImageURL:l,tags:e,likes:t,views:a,comments:m,downloads:A}=r;return n.push(`<li class="gallery-item">
         <a class="gallery-link" href="${l}">
           <img
             class="gallery-image"
             src="${s}"
             alt="${e}"
           />
           <ul class="desc">
               <li class="descel"><span class="bold">Likes:</span> ${t}</li>
               <li class="descel"><span class="bold">Views:</span> ${a}</li>
               <li class="descel"><span class="bold">Comments:</span> ${m}</li>
               <li class="descel"><span class="bold">Downloads:</span> ${A}</li>
             </ul>
         </a>
       </li>`)}),f.insertAdjacentHTML("beforeend",n.join(""))},c="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEZSURBVHgBrZVRDoMgDIar0fi6m2xH2Y3Ek2w3cFfZXXwBljFQCai0xemfoCaU/xNpKwAirXWrlDY5w8ViPhVmbgwIO14A3zeQKq/2IuwaqOu6A07+zaVUT8iUi+V28rd5NuSIOQs5wxyFUOZKqRtnmIpZQCZz3acWcgcXUjkF0b2bmwFSpAxskMAgYecaWSsFC8AgnHkMqIBR09TCGrnHsZic5iLs3By3ngWsITMgy9yphEyVJZjUM6esHUS9yfea7N7DAmJz/1niM2EhVBZR2UKl8DS/SFO80OhUnCBkoYWgz2MdNAx8q0jFOK/Fy1GQvdqYe50BQc3PgLDmRyCU+aYOfFsoCtPa+yXvp2/ue9rHqLATflCf5QflVUcNIrzeSwAAAABJRU5ErkJggg==",g=document.querySelector(".form"),d=document.querySelector("[name=search-text]"),y=document.querySelector(".gallery");g.addEventListener("submit",o=>{g.insertAdjacentHTML("afterend",'<div class="loader"></div>');const r=document.querySelector(".loader");if(o.preventDefault(),y.innerHTML="",d.value.trim().length===0){i.show({title:"Error",message:"Please enter your request",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:c,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}F(d.value).then(s=>{if(s.length===0){i.show({title:"😢",message:"Sorry, there are no images matching your search query. Please try again!",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:c,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}console.log(s),r.remove(),h(s),S.refresh()}).catch(s=>{console.log(s)})});let S=new p(".gallery a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=index.js.map
